export const LOAN_CONSTANTS = {
  STATUS: {
    ACTIVE: 'ACTIVE',
    OVERDUE: 'OVERDUE',
    DEFAULTED: 'DEFAULTED',
    PAID_OFF: 'PAID_OFF',
    RESTRUCTURED: 'RESTRUCTURED'
  },
  SUBSTATUS: {
    CURRENT: 'CURRENT',
    GRACE_PERIOD: 'GRACE_PERIOD',
    DELINQUENT: 'DELINQUENT'
  },
  REPAYMENT_FREQUENCY: {
    WEEKLY: 'WEEKLY',
    MONTHLY: 'MONTHLY',
    QUARTERLY: 'QUARTERLY'
  },
  TYPE: {
    FIXED: 'FIXED',
    FLEXIBLE: 'FLEXIBLE'
  }
};

export const PAGINATION_DEFAULTS = {
  PAGE: 1,
  LIMIT: 10,
  MAX_LIMIT: 100
};