version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: customer_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: microfinance
    volumes:
      - mongodb_data:/data/db
    networks:
      - customer_network

  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    container_name: customer_service
    restart: unless-stopped
    ports:
      - "50051:50051"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/microfinance?authSource=admin
    depends_on:
      - mongodb
    networks:
      - customer_network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user_service
    restart: unless-stopped
    ports:
      - "50052:50052"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/microfinance?authSource=admin
    depends_on:
      - mongodb
    networks:
      - customer_network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth_service
    restart: unless-stopped
    ports:
      - "50053:50053"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=microfinance-secret-key
      - JWT_EXPIRES_IN=24h
    depends_on:
      - user-service
    networks:
      - customer_network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - customer-service
      - user-service
      - auth-service
    networks:
      - customer_network

volumes:
  mongodb_data:
    driver: local

networks:
  customer_network:
    driver: bridge